### ISSUE TITLE
Internal server error everywhere

### ISSUE THREAD

**Issue by plexish** [WikiApiary/WikiApiary#131]
Trying to load any page gives:

```
[45486c70] /wiki/Main_Page Exception from line 75 of /srv/www/mediawiki/public_html/w/includes/clientpool/RedisConnectionPool.php: RedisConnectionPool requires a Redis client library. See https://www.mediawiki.org/wiki/Redis#Setup

Backtrace:

#0 /srv/www/mediawiki/public_html/w/includes/clientpool/RedisConnectionPool.php(129): RedisConnectionPool->__construct(array)
#1 /srv/www/mediawiki/public_html/w/includes/objectcache/RedisBagOStuff.php(64): RedisConnectionPool::singleton(array)
#2 /srv/www/mediawiki/public_html/w/includes/objectcache/ObjectCache.php(88): RedisBagOStuff->__construct(array)
#3 /srv/www/mediawiki/public_html/w/includes/objectcache/ObjectCache.php(72): ObjectCache::newFromParams(array)
#4 /srv/www/mediawiki/public_html/w/includes/objectcache/ObjectCache.php(44): ObjectCache::newFromId(string)
#5 /srv/www/mediawiki/public_html/w/includes/GlobalFunctions.php(3961): ObjectCache::getInstance(string)
#6 /srv/www/mediawiki/public_html/w/includes/Setup.php(513): wfGetMainCache()
#7 /srv/www/mediawiki/public_html/w/includes/WebStart.php(156): require_once(string)
#8 /srv/www/mediawiki/public_html/w/index.php(43): require(string)
#9 {main}
```

Just in case you check here first.

**Comment by jthingelstad** [comment]
You caught me in the middle of moving all caching from memcached to redis. It’s done now.

**Comment by plexish** [comment]
Okay, glad it's nothing worrying :)

**Comment by jthingelstad** [comment]
Well, tons of stuff may be broken now with redis so we'll see how worried we should be. :-)

**Comment by kghbln** [comment]
There is something in the water. The job queue is hitting the sky since the change to redis.

**Comment by jthingelstad** [comment]
Job queue issue commented on in #136.
