### ISSUE TITLE
Internal error / SF_FormUtils.php(428): Parser->parse / Parser state cleared while parsing

### ISSUE THREAD

**Issue by mwjames** [WikiApiary/WikiApiary#209]
When trying to display https://wikiapiary.com/wiki/WikiApiary the following error is issued:

```
Internal error

[7f9101bd] /wiki/WikiApiary Exception from line 6347 of /srv/www/mediawiki/public_html/w/includes/parser/Parser.php: Parser state cleared while parsing. Did you call Parser::parse recursively?

Backtrace:

#0 /srv/www/mediawiki/public_html/w/includes/parser/Parser.php(374): Parser->lock()
#1 /srv/www/mediawiki/public_html/w/extensions/SemanticForms/includes/SF_FormUtils.php(428): Parser->parse(string, Title, ParserOptions)
#2 /srv/www/mediawiki/public_html/w/extensions/SemanticForms/includes/SF_FormPrinter.php(501): SFFormUtils::getFormDefinition(Parser, string, NULL)
#3 /srv/www/mediawiki/public_html/w/extensions/SemanticForms/includes/SF_FormLinker.php(174): SFFormPrinter->formHTML(string, boolean, boolean, NULL, NULL, string, NULL)
#4 /srv/www/mediawiki/public_html/w/extensions/SemanticForms/includes/SF_FormLinker.php(295): SFFormLinker::createLinkedPage(Title, array)
#5 [internal function]: SFFormLinker::setBrokenLink(DummyLinker, Title, array, string, array, NULL)
#6 /srv/www/mediawiki/public_html/w/includes/Hooks.php(206): call_user_func_array(string, array)
#7 /srv/www/mediawiki/public_html/w/includes/GlobalFunctions.php(3995): Hooks::run(string, array, NULL)
#8 /srv/www/mediawiki/public_html/w/includes/Linker.php(252): wfRunHooks(string, array)
#9 /srv/www/mediawiki/public_html/w/includes/parser/LinkHolderArray.php(425): Linker::link(Title, string, array, array, array)
#10 /srv/www/mediawiki/public_html/w/includes/parser/LinkHolderArray.php(276): LinkHolderArray->replaceInternal(string)
#11 /srv/www/mediawiki/public_html/w/includes/parser/Parser.php(5231): LinkHolderArray->replace(string)
#12 /srv/www/mediawiki/public_html/w/includes/parser/Parser.php(423): Parser->replaceLinkHolders(string)
#13 [internal function]: Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#14 /srv/www/mediawiki/public_html/w/includes/StubObject.php(105): call_user_func_array(array, array)
#15 /srv/www/mediawiki/public_html/w/includes/StubObject.php(125): StubObject->_call(string, array)
#16 /srv/www/mediawiki/public_html/w/includes/content/WikitextContent.php(338): StubObject->__call(string, array)
#17 /srv/www/mediawiki/public_html/w/includes/content/WikitextContent.php(338): StubObject->parse(string, Title, ParserOptions, boolean, boolean, integer)
#18 /srv/www/mediawiki/public_html/w/includes/content/AbstractContent.php(490): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#19 /srv/www/mediawiki/public_html/w/includes/poolcounter/PoolWorkArticleView.php(139): AbstractContent->getParserOutput(Title, integer, ParserOptions)
#20 /srv/www/mediawiki/public_html/w/includes/poolcounter/PoolCounterWork.php(123): PoolWorkArticleView->doWork()
#21 /srv/www/mediawiki/public_html/w/includes/page/Article.php(688): PoolCounterWork->execute()
#22 /srv/www/mediawiki/public_html/w/includes/actions/ViewAction.php(44): Article->view()
#23 /srv/www/mediawiki/public_html/w/includes/MediaWiki.php(414): ViewAction->show()
#24 /srv/www/mediawiki/public_html/w/includes/MediaWiki.php(282): MediaWiki->performAction(Article, Title)
#25 /srv/www/mediawiki/public_html/w/includes/MediaWiki.php(584): MediaWiki->performRequest()
#26 /srv/www/mediawiki/public_html/w/includes/MediaWiki.php(435): MediaWiki->main()
#27 /srv/www/mediawiki/public_html/w/index.php(46): MediaWiki->run()
#28 {main}
```

**Comment by mwjames** [comment]
@s7eph4n FYI

**Comment by jthingelstad** [comment]
Weird. Surprising I didn’t see this before. Everything was working fine and then this happened. Anyway, I did a `git pull` on Semantic Forms `Updating 3b6a3b4..e66520f` and it resolved. Also grabbed SemanticFormsInputs `Updating d480913..e733bd2` while I was at it. For some reason I didn’t update these two thinking they were handled by composer.

**Comment by jthingelstad** [comment]
Wonder if there was something cached that kept this from being a problem sooner after I upgraded.

**Comment by s7eph4n** [comment]
There was a change in newer version of MW's parser that prevents restarting the parse (see call to `Parser->lock()` in the backtrace above).

SF until very recently did exactly that: To parse it's forms it called Parser::parse() instead of Parser::recursiveTagParse(). It's fixed since a week or so.
