### ISSUE TITLE
Uploading files fails

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/WikiApiary#238]
**Issue:**
[49d2fa18] /wiki/Special:UploadWindow MWException from line 1856 of /.../w/includes/filerepo/file/LocalFile.php: Could not acquire lock for 'Peacetechwikilogo.png.'

**Backtrace:**

```
#0 /.../w/includes/filerepo/file/LocalFile.php(1148): LocalFile->lock()
#1 /.../w/includes/upload/UploadBase.php(723): LocalFile->upload(string, string, string, integer, array, boolean, User)
#2 /.../w/extensions/SemanticForms/specials/SF_UploadWindow.php(362): UploadBase->performUpload(string, string, boolean, User)
#3 /.../w/extensions/SemanticForms/specials/SF_UploadWindow.php(150): SFUploadWindow->processUpload()
#4 /.../w/includes/specialpage/SpecialPage.php(384): SFUploadWindow->execute(NULL)
#5 /.../w/includes/specialpage/SpecialPageFactory.php(582): SpecialPage->run(NULL)
#6 /.../w/includes/MediaWiki.php(267): SpecialPageFactory::executePath(Title, RequestContext)
#7 /.../w/includes/MediaWiki.php(566): MediaWiki->performRequest()
#8 /.../w/includes/MediaWiki.php(414): MediaWiki->main()
#9 /.../w/index.php(41): MediaWiki->run()
#10 {main}
```

**Comment by hexmode** [comment]
try again?

**Comment by kghbln** [comment]
Cool, up and running again. Thanks a lot!
