### ISSUE TITLE
Reconnect to MySQL if apiary_db loses connection

### ISSUE THREAD

**Issue by jthingelstad** [WikiApiary/WikiApiary#42]
If the connection to MySQL is dropped runSql will report exception that "SQL Server has gone away". This should be detected and then reconnect to the database.

**Comment by jthingelstad** [comment]
@optimuspaul any suggestions on the best place to handle this? Since the SQL connection is in `connect_mysql.py` and not executed again, wondering if I should move it to a function so I can reinitialize as needed.

**Comment by optimuspaul** [comment]
You could also wrap it in an object that does automatic reconnects.  Both seem like about the same amount of work, but auto-reconnect would be more maintainable I think.

**Comment by jthingelstad** [comment]
```
[2014-08-05 19:31:43,034: ERROR/MainProcess] Task apiary.tasks.website.statistics.GetStatisticsTask[fe60166d-b51b-4f6a-ba7c-b60127bc8731] raised unexpected: Exception(OperationalError(2006, 'MySQL server has gone away'),)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/jamie/Projects/WikiApiary/apiary/tasks/website/statistics.py", line 180, in run
    self.runSql(sql_command)
  File "/Users/jamie/Projects/WikiApiary/apiary/tasks/__init__.py", line 89, in runSql
    raise Exception(e)
Exception: (2006, 'MySQL server has gone away')
```

**Comment by optimuspaul** [comment]
Should be good to go now. Tests all passed.

**Comment by jthingelstad** [comment]
Fixed! Validated by running and stopping/starting mysqld and was able to reconnect and proceed.
